blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path("post/", views.PostLV.as_view(), name="post_list"),
    # Example: /blog/post/django-example/
    re_path(r"^post/(?P<slug>[-\w]+)/$",
            views.PostDV.as_view(), name="post_detail"),
    # Example: /blog/archive/
    path("archive/", views.PostAV.as_view(), name="post_archive"),
    # Example: /blog/archive/2019
    path("archive/<int:year>/", views.PostYAV.as_view(), name="post_year_archive"),
    # Example: /blog/archive/2019/nov/
    path("archive/<int:year>/<str:month>/",
         views.PostMAV.as_view(), name="post_month_archive"),
    # Example: /blog/archive/2019/nov/10/
    path("archive/<int:year>/<str:month>/<int:day>/",
         views.PostDAV.as_view(), name="post_day_archive"),
    # Example: /blog/archive/today/
    path("archive/today/", views.PostTAV.as_view(), name="post_today_archive"),
    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # Example: /blog/tag/tagname
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(),
         name='tagged_object_list'),
    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name="search"),
    # Example: /blog/add/
    path("add/", views.PostCreateView.as_view(), name="add",),
    # Example: /blog/change/
    path("change/", views.PostChangeLV.as_view(), name="change",),
    # Example: /blog/99/update/
    path("<int:pk>/update/", views.PostUpdateView.as_view(), name="update",),
    # Example: /blog/99/delete/
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete",),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include  # 3장에서 include 추가
from mysite.views import HomeView  # 4장에서 추가
# from bookmark.views import BookmarkLV, BookmarkDV # 삭제
from mysite.views import UserCreateView, UserCreateDoneTV  # 10장 추가


urlpatterns = [
    path('admin/', admin.site.urls),

    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("accounts/register/done/",
         UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),  # 4장에서 추가
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    # class-based views
    # path('bookmark/', BookmarkLV.as_view(), name='index'), # 삭제
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'), # 삭제
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'
urlpatterns = [
    # Example: /photo/
    path('', views.AlbumLV.as_view(), name="index"),
    # Example: /photo/album/, same as /photo/
    path('album/', views.AlbumLV.as_view(), name='album_list'),
    # Example: /photo/album/99/
    path("album/<int:pk>/", views.AlbumDV.as_view(), name="album_detail"),
    # Example: /photo/photo/99/
    path("photo/<int:pk>/", views.PhotoDV.as_view(), name="photo_detail"),
    # Example: /photo/album/add/
    path("album/add/", views.AlbumPhotoCV.as_view(), name="album_add"),
    # Example: /photo/album/change
    path("album/change/", views.AlbumChangeLV.as_view(), name="album_change"),
    # Example: /photo/album/99/update
    path("album/<int:pk>/update/",
         views.AlbumPhotoUV.as_view(), name="album_update"),
    # Example: /photo/album/99/delete/
    path("album/<int:pk>/delete/", views.AlbumDelV.as_view(), name="album_delete"),
    # Example: /photo/photo/add/
    path("photo/add/", views.PhotoCV.as_view(), name="photo_add"),
    # Example: /photo/photo/change/
    path("photo/change/", views.PhotoChangeLV.as_view(), name="photo_change"),
    # Example: /photo/photo/99/update/
    path("photo/<int:pk>/update/", views.PhotoUV.as_view(), name="photo_update"),
    # Example: /photo/photo/99/delete/
    path("photo/<int:pk>/delete/", views.PhotoDelV.as_view(), name="photo_delete"),
]

photo/models.py
from django.db import models
from django.urls import reverse

from photo.fields import ThumbnailImageField


# Create your models here.
class Album(models.Model):
    name = models.CharField(max_length=30)
    description = models.CharField(
        'One Line Description', max_length=100, blank=True)
    owner = models.ForeignKey(
        'auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("photo:album_detail", args=(self.id,))


class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    title = models.CharField('TITLE', max_length=30)
    description = models.TextField('Photo Description', blank=True)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    upload_dt = models.DateTimeField("Upload Date", auto_now_add=True)
    owner = models.ForeignKey(
        'auth.User', on_delete=models.CASCADE, verbose_name='OWNER', blank=True, null=True)

    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("photo:photo_detail", args=(self.id,))

photo/forms.py
from django.forms import inlineformset_factory
from photo.models import Album, Photo


PhotoInlineFormSet = inlineformset_factory(
    Album, Photo, fields=['image', 'title', 'description'], extra=2)

photo/views.py
# from django.shortcuts import render
from django.views.generic import ListView, DetailView
from photo.models import Album, Photo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from mysite.views import OwnerOnlyMixin
from photo.forms import PhotoInlineFormSet


# Create your views here.
class AlbumLV(ListView):
    model = Album


class AlbumDV(DetailView):
    model = Album


class PhotoDV(DetailView):
    model = Photo


# --- Create/Change-list/Update/Delete for Photo
class PhotoCV(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class PhotoChangeLV(LoginRequiredMixin, ListView):
    model = Photo
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)


class PhotoUV(OwnerOnlyMixin, UpdateView):
    model = Photo
    fields = ('album', 'title', 'image', 'description')
    success_url = reverse_lazy('photo:index')


class PhotoDelV(OwnerOnlyMixin, DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:index')


# --- Change-list/Delete for Album
class AlbumChangeLV(LoginRequiredMixin, ListView):
    model = Album
    template_name = 'photo/album_change_list.html'

    def get_queryset(self):
        return Album.objects.filter(owner=self.request.user)


class AlbumDelV(OwnerOnlyMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('photo:index')


# --- (InlineFormSet) Create/Update for album
class AlbumPhotoCV(LoginRequiredMixin, CreateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(
                self.request.POST, self.request.FILES)
        else:
            context['formset'] = PhotoInlineFormSet()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context['formset']
        for photoform in formset:
            photoform.instance.owner = self.request.user
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))


class AlbumPhotoUV(OwnerOnlyMixin, UpdateView):
    model = Album
    fields = ('name', 'description')
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = PhotoInlineFormSet(
                self.request.POST, self.request.FILES, instance=self.object)
        else:
            context['formset'] = PhotoInlineFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

photo/templates/photo/album_change_list.html
{% extends 'base.html' %}

{% block title %}
    album_change_list.html
{% endblock title %}

{% block content %}
    <h1>Album Change - {{ user }}</h1>

    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr class="table-success">
                <th>Name</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'photo:album_update' item.id %}">Update</a></td>
                    <td><a href="{% url 'photo:album_delete' item.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

photo/templates/photo/album_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    album_confirm_delete.html
{% endblock title %}

{% block content %}
    <h1>Album Delete <small class="font-italic">(including related photos)</small></h1>
    <br>

    <form action="." method="post">
        {% csrf_token %}
        <p>Are you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
    </form>
{% endblock content %}

photo/templates/photo/album_detail.html
{% extends 'base.html' %}

{% block title %}
    album_detail.html
{% endblock title %}

{% block extra-style %}
    <style>
        .thumbnail {
            border: 5px solid #ccc;
        }
    </style>
{% endblock extra-style %}

{% block content %}
    <div class="mt-5">
        <span class="h2">{{ object.name }}&emsp;</span>
        <span class="h5" font-italic>{{ object.description }}</span>
    </div>

    <hr style="margin: 0 0 20px 0;">

    <div class="row">
        {% for photo in object.photo_set.all %}
            <div class="col-md-3 mb-5">
                <div class="thumbnail">
                    <a href="{{ photo.get_absolute_url }}">
                        <img src="{{ photo.image.thumb_url }}" style="width: 100%;">
                    </a>
                </div>
                <ul>
                    <li class="font-italic">{{ photo.title }}</li>
                    <li class="font-italic">{{ photo.upload_dt|date:"Y-m-d" }}</li>
                </ul>
            </div>    
        {% endfor %}
    </div>
{% endblock content %}

photo/templates/photo/album_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <h1>Album-Photo Create/Update - {{ user }}</h1>
    <p class="font-italic">This is a creation or update form for your album using PhotoInlineFormSet.</p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the form error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}

    {% if formset.errors %}
        <div class="alert alert-warning">
            <div class="font-weight-bold">Wrong! Please correct the formset error(s) below.</div>
            {% for formerrors in formset.errors %}
                {{ formerrors }}
            {% endfor %}
        </div>
    {% endif %}

    {% if form.is_multipart or formset.is_multipart %}
        <form action="" method="post" enctype="multipart/form-data">
    {% else %}
        <form action="." method="post">
    {% endif %}
        {% csrf_token %}
            <h4>create or update album contents</h4>
            <fieldset class="card pt-3">
                <div class="form-group row">
                    {{ form.name|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.name|add_class:"form-control"|attr:"autofocus" }}
                    </div>
                </div>

                <div class="form-group row">
                    {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.description|add_class:"form-control" }}
                    </div>
                </div>
            </fieldset>
            <br>

            <h4>create or update photo contents</h4>

            <fieldset class="card pt-3">
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form.id }}
                    {# form.album #}
                <div class="form-group row">
                    {{ form.image|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.image|add_class:"form-control-file" }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ form.title|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-5">
                        {{ form.title|add_class:"form-control" }}
                    </div>
                </div>
                <div class="form-group row">
                    {{ form.description|add_label_class:"col-form-label col-sm-3 ml-3 font-weight-bold" }}
                    <div class="col-sm-8">
                        {{ form.description|add_class:"form-control"|attr:"row:3" }}
                    </div>
                </div>

                <hr>
                {% endfor %}
            </fieldset>

            <div class="form-group card py-1">
                <div class="offset-sm-3 col-sm-5">
                    <input type="submit" value="Submit" class="btn btn-info">
                </div>
            </div>
        </form>
{% endblock content %}

photo/templates/photo/album_list.html
{% extends 'base.html' %}

{% block title %}
    album_list
{% endblock title %}

{% block extra-style %}
    <style>
        thumbnail {
            border: 3px solid #ccc;
        }
    </style>
{% endblock extra-style %}

{% block content %}
    {% for item in object_list %}
        <div class="mt-5">
            <a href="{% url 'photo:album_detail' item.id %}" class="h2">
                {{ item.name }}
            </a>&emsp;
            <span class="font-italic h5">{{ item.description }}</span>
        </div>

        <hr style="margin: 0 0 20px 0;">

        <div class="row">
            {% for photo in item.photo_set.all|slice:":5" %}
                <div class="ml-5">
                    <div class="thumbnail">
                        <a href="{{ photo.get_absolute_url }}">
                            <img src=" {{ photo.image.thumb_url }}" style="width: 100%;">
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock content %}

photo/templates/photo/photo_change_list.html
{% extends 'base.html' %}

{% block title %}
    photo_change_list.html
{% endblock title %}

{% block content %}
    <h1>Photo Change - {{ user }}</h1>

    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr class="table-info">
                <th>Album</th>
                <th>Title</th>
                <th>Description</th>
                <th>Owner</th>
                <th>Update</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            {% for item in object_list %}
                <tr>
                    <td>{{ item.album }}</td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.description }}</td>
                    <td>{{ item.owner }}</td>
                    <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
                    <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

photo/templates/photo/photo_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    photo_confirm_delete.html                         
{% endblock title %}

{% block content %}
    <h1>Photo Delete</h1>
    <br>
    
    <form action="." method="post">
        {% csrf_token %}
        <p>Are you sure want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm">
    </form>
{% endblock content %}

photo/templates/photo/photo_detail.html
{% extends 'base.html' %}

{% block title %}
    photo_detail.html
{% endblock title %}

{% block content %}
    <h2 class="mt-5">
        {{ object.title }}
    </h2>
    <dib class="row">
        <div class="col-md-9">
            <a href="{{ object.image.url }}">
                <img src="{{ object.image.url }}" style="width: 100%">
            </a>
        </div>

        <ul class="col-md-3 mt-3">
            <li class="h5">Photo Description</li>
                {% if object.description %}<p>{{ object.description|linebreaks }}</p>
                {% else %}  <p>(blank)</p> {% endif %}
            <li class="h5">Date Uploaded</li>
                <p class="font-italic">{{ dbject.upload_dt }}</p>
            <li class="h5">Alumb Name</li>
                <p class="font-ltalic">
                    <a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a>
                </p>
        </ul>
    </dib>
{% endblock content %}

photo/templates/photo/photo_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
    photo_form.html
{% endblock title %}

{% block content %}
    <h1>Photo Create/Update - {{ user }}</h1>
    <p class="font-italic">This is a creation or form for your photo.</p>

    {% if form.errors %}
        <div class="alert alert-danger">
            <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
            {{ form.errors }}
        </div>
    {% endif %}

    {% if form.is_multipart %}
        <form action="" method="post" enctype="multipart/form-data" class="card pt-3">
    {% else %}
        <form action="." method="post" class="card pt-3">
    {% endif %}
    {% csrf_token %}
            <div class="form-group row">
                {{ form.album|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-2">
                    {{ form.album|add_class:"form-control" }}
                </div>
                <div class="col-sm-2 my-auto">
                    <a href="{% url 'photo:album_add' %}" class="btn btn-outline-primary btn-sm">ADD Album</a>
                </div>
            </div>
            <div class="form-group row">
                {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control"|attr:"autofocus" }}
                </div>
            </div>
            <div class="form-group row">
                {{ form.image|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-5">
                    {{ form.image|add_class:"form-control-file" }}
                </div>
            </div>
            <div class="form-group row">
                {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
                <div class="col-sm-8">
                    {{ form.description|add_class:"form-control"|attr:"rows:3" }}
                </div>
            </div>
            <div class="form-group">
                <div class="offset-sm-2 col-sm-5">
                    <input type="submit" value="Submit" class="btn btn-info">
                </div>
            </div>
        </form>
{% endblock content %}