blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # Example: /blog/
    path('', views.PostLV.as_view(), name='index'),

    # Example: /blog/post/ (same as /blog/)
    path("post/", views.PostLV.as_view(), name="post_list"),
    # Example: /blog/post/django-example/
    re_path(r"^post/(?P<slug>[-\w]+)/$",
            views.PostDV.as_view(), name="post_detail"),
    # Example: /blog/archive/
    path("archive/", views.PostAV.as_view(), name="post_archive"),
    # Example: /blog/archive/2019
    path("archive/<int:year>/", views.PostYAV.as_view(), name="post_year_archive"),
    # Example: /blog/archive/2019/nov/
    path("archive/<int:year>/<str:month>/",
         views.PostMAV.as_view(), name="post_month_archive"),
    # Example: /blog/archive/2019/nov/10/
    path("archive/<int:year>/<str:month>/<int:day>/",
         views.PostDAV.as_view(), name="post_day_archive"),
    # Example: /blog/archive/today/
    path("archive/today/", views.PostTAV.as_view(), name="post_today_archive"),
    # Example: /blog/tag/
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # Example: /blog/tag/tagname
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(),
         name='tagged_object_list'),
    # Example: /blog/search/
    path('search/', views.SearchFormView.as_view(), name="search"),
    # Example: /blog/add/
    path("add/", views.PostCreateView.as_view(), name="add",),
    # Example: /blog/change/
    path("change/", views.PostChangeLV.as_view(), name="change",),
    # Example: /blog/99/update/
    path("<int:pk>/update/", views.PostUpdateView.as_view(), name="update",),
    # Example: /blog/99/delete/
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name="delete",),
]

bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV # 11장에서 삭제
from bookmark import views

app_name = 'bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    # Example: /bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name="add",),
    # Example: /bookmark/change
    path('change/', views.BookmarkChangeLV.as_view(), name="change",),
    # Example: /bookmark/99/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update",),
    # Example: /bookmark/99/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete",),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include  # 3장에서 include 추가
from mysite.views import HomeView  # 4장에서 추가
# from bookmark.views import BookmarkLV, BookmarkDV # 삭제
from mysite.views import UserCreateView, UserCreateDoneTV  # 10장 추가


urlpatterns = [
    path('admin/', admin.site.urls),

    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/register/", UserCreateView.as_view(), name="register"),
    path("accounts/register/done/",
         UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),  # 4장에서 추가
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),

    # class-based views
    # path('bookmark/', BookmarkLV.as_view(), name='index'), # 삭제
    # path('bookmark/<int:pk>/', BookmarkDV.as_view(), name='detail'), # 삭제
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'
urlpatterns = [
    # Example: /photo/
    path('', views.AlbumLV.as_view(), name="index"),
    # Example: /photo/album/, same as /photo/
    path('album/', views.AlbumLV.as_view(), name='album_list'),
    # Example: /photo/album/99/
    path("album/<int:pk>/", views.AlbumDV.as_view(), name="album_detail"),
    # Example: /photo/photo/99/
    path("photo/<int:pk>/", views.PhotoDV.as_view(), name="photo_detail"),
    # Example: /photo/album/add/
    path("album/add/", views.AlbumPhotoCV.as_view(), name="album_add"),
    # Example: /photo/album/change
    path("album/change/", views.AlbumChangeLV.as_view(), name="album_change"),
    # Example: /photo/album/99/update
    path("album/<int:pk>/update/",
         views.AlbumPhotoUV.as_view(), name="album_update"),
    # Example: /photo/album/99/delete/
    path("album/<int:pk>/delete/", views.AlbumDelV.as_view(), name="album_delete"),
    # Example: /photo/photo/add/
    path("photo/add/", views.PhotoCV.as_view(), name="photo_add"),
    # Example: /photo/photo/change/
    path("photo/change/", views.PhotoChangeLV.as_view(), name="photo_change"),
    # Example: /photo/photo/99/update/
    path("photo/<int:pk>/update/", views.PhotoUV.as_view(), name="photo_update"),
    # Example: /photo/photo/99/delete/
    path("photo/<int:pk>/delete/", views.PhotoDelV.as_view(), name="photo_delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %}Django Web Programming{% endblock title %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block extra-style %}
    {% endblock extra-style %}
</head>
<body style="padding-top:100px;">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn bg-dark"><a href="{% url 'home' %}" class="nav-link text-white">Home</a></li>
                <li class="nav-item mx-1 btn bg-dark"><a href="{% url 'bookmark:index' %}" class="nav-link text-white">Bookmark</a></li>
                <li class="nav-item mx-1 btn bg-dark"><a href="{% url 'blog:index' %}" class="nav-link text-white">Blog</a></li>
                <li class="nav-item mx-1 btn bg-dark"><a href="{% url 'photo:index' %}" class="nav-link text-white">Photo</a></li>
                {% comment %} 메인 메뉴 Add 추가 {% endcomment %}
                <li class="nav-item dropdown mx-1 btn bg-dark">
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">Add</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'bookmark:add' %}" class="dropdown-item">Bookmark</a>
                        <a href="{% url 'blog:add' %}" class="dropdown-item">Post</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'photo:album_add' %}" class="dropdown-item">Album</a>
                        <a href="{% url 'photo:photo_add' %}" class="dropdown-item">Photo</a>
                    </div>
                </li>
                {% comment %} 메인 메뉴 Change 수정 {% endcomment %}
                <li class="nav-item dropdown mx-1 btn bg-dark">
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">Change</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'bookmark:change' %}" class="dropdown-item">Bookmark</a>
                        <a href="{% url 'blog:change' %}" class="dropdown-item">Post</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'photo:album_change' %}" class="dropdown-item">Album</a>
                        <a href="{% url 'photo:photo_change' %}" class="dropdown-item">Photo</a>
                    </div>
                </li>
                <li class="nav-item dropdown mx-1 btn bg-dark">
                    <a href="#" class="nav-link dropdown-toggle text-white" data-toggle="dropdown">Util</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'admin:index' %}" class="dropdown-item">Admin</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'blog:post_archive' %}" class="dropdown-item">Archive</a>
                        <a href="{% url 'blog:search' %}" class="dropdown-item">Search</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2" acrion="" method="post">
                {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
            </form>
            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn btn-btn-primary">
                    {% if user.is_active %}
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle text-white">
                            <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;
                        </a>
                        <div class="dropdown-menu">
                            <a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
                            <a href="{% url 'password_change' %}" class="dropdown-item">Change Password</a>
                        </div>
                    {% else %}
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle text-white">
                            <i class="fas fa-user"></i>&ensp;Anonymous&ensp;
                        </a>
                        <div class="dropdown-menu">
                            <a href="{% url 'login' %}" class="dropdown-item">Login</a>
                            <a href="{% url 'register' %}" class="dropdown-item">Register</a>
                        </div>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    {% block footer %}
    {% endblock footer %}
    

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0cf4c20639.js"></script>
    {% block extra-script %}
    {% endblock extra-script %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}home.html{% endblock title %}

{% block extra-style %}
    <style type="text/css">
        .home-image {
            background-image: url("{% static '../static/img/sleeping.jpg' %}");
            background-repeat: no-repeat;
            background-postion: center;
            background-size: cover;
            height: 500px;
            border-top: 10px solid #ccc;
            borer-bottom: 10px solid #ccc;
            padding: 20px 0 0 20px;
        }
        .title {
            color: #c80;
            font-weight: bold;
        }
        .powered {
            position: relative;
            top: 77%;
            color: #cc0;
            font-style: italic;
        }
    </style>
{% endblock extra-style %}

{% block content %}
    <div class="home-image">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-arrow-circle-right"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Bookmark App</h3>
            <p>
                Bookmark is Uniform Resource Identifier (URI)
                that is stored for later retrieval in any of various storage formats. 
                You can store your own bookmarks by Bookmark application.
                It's also possible to update or delete your bookmarks.
            </p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>
                This application makes it possible to log daily events or write your own interests such as bobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages, and other media related to its topic.
            </p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="fixed-bottom bg-info">
        <div class="text-white font-italic text-right mr-5">Copyright &copy; 2019 DjangoBook by Jungbin</div>
    </footer>
{% endblock footer %}